FROM python:3.6.0b4-alpine

ENTRYPOINT ["dumb-init", "--"]
CMD ["deck-chores"]
ENV DEBUG=true

RUN apk add --no-cache --virtual .build-deps build-base \
 && apk add --no-cache ca-certificates \
 && pip install  cerberus dumb-init docker-py APScheduler \
 && apk del .build-deps

COPY . /src

RUN cd src && python setup.py install \
 && cd / && rm -R /src
