#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"

BASE_IMAGE=$(head -n1 Dockerfile | cut -d" " -f2)
docker pull $BASE_IMAGE
printenv
docker build \
    --build-arg BUILD_DATE="$(date --rfc-3339 seconds)" \
    --build-arg SOURCE_COMMIT="${GIT_SHA1}" \
    --build-arg VERSION=$(grep "VERSION = " setup.py | cut -d"=" -f2 | tr -d " '") \
    --tag $IMAGE_NAME \
    .

echo "------ HOOK END - BUILD -------"
