#!/usr/bin/sh

set -ex

for ARCH in arm64 armv7l ; do

BUILD_HOST="${ARCH}-host"
REMOTE_PATH="docker/images/deck-chores"
IMAGE_NAME="$1-${ARCH}"
SOURCE_COMMIT=$2

rsync -e ssh -vca --filter=':- .gitignore' --exclude='.git/' --del . $BUILD_HOST:~/$REMOTE_PATH

ssh $BUILD_HOST <<-SCRIPT
    cd ${REMOTE_PATH}
    IMAGE_NAME="${IMAGE_NAME}" GIT_SHA1="${SOURCE_COMMIT}" hooks/build
    docker push "${IMAGE_NAME}"
SCRIPT

done
