#!/bin/sh

set -e

IMAGE=$1
VERSION=$2

MANIFEST="${IMAGE}:${VERSION}"

AMD64_IMAGE="${IMAGE}:${VERSION}-amd64"
ARMV7L_IMAGE="${IMAGE}:${VERSION}-armv7l"

while ! docker pull ${AMD64_IMAGE} ; do sleep 10 ; done
while ! docker pull ${ARMV7L_IMAGE} ; do sleep 10 ; done

docker manifest create "${MANIFEST}" "${AMD64_IMAGE}" "${ARMV7L_IMAGE}"
docker manifest annotate --arch "amd64" "${MANIFEST}" "${AMD64_IMAGE}"
docker manifest annotate --arch "arm" --variant "v7" "${MANIFEST}" "${ARMV7L_IMAGE}"

docker manifest inspect "${MANIFEST}"
docker manifest push "${MANIFEST}"
